import { Roboto, Inter } from "next/font/google";
import '@/styles/globals.css';
import '@/styles/fonts.css'
import '@/styles/colors.css'
import '@/styles/components.css'
import '@/styles/screenCoeff.css'

import AppLayoutWrapper from "@/components/layout/AppLayoutWrapper";

const inter = Inter({
  subsets: ["latin"],
})

const roboto = Roboto({
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${inter.variable} ${roboto.className}`}>
        <AppLayoutWrapper >
          {children}
        </AppLayoutWrapper>
      </body>
    </html>
  );
}
